WORKSPACE=$PWD/workspace
OTP_24_INSTALL=$WORKSPACE/otp_24.1.3_install
OTP_24_BIN_DIR=$OTP_24_INSTALL/bin
OTP_24_SRC=$WORKSPACE/otp_24.1.3_src
ELIXIR_SRC=$WORKSPACE/elixir
ELIXIR_BIN_DIR=$ELIXIR_SRC/bin

PATH=$OTP_24_BIN_DIR:$ELIXIR_BIN_DIR:$PATH